### PR TITLE
updates to UG, minor Ui fixes, add partial date validation, new implementation of force cancel

### LINKED ISSUE #174: [PE-D] Weird string in user guide
Under Quick start section, there is a weird string display. Perhaps missing the closing "```" .

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: tryyang2001/ped#2

### LINKED ISSUE #211: add date validation for user-added date
fixes #176, #187, #188

### PR DESCRIPTION
**Pull request by yeezao**
Fixes: #174 #201 #207 #210 

Partially fixes #211 - only dates before epoch will be rejected, other invalid dates may still be parsed.

### CODE REVIEW

**Review by leeyikai — APPROVED** [review]
LGTM

File: src/main/java/seedu/duke/Storage.java [hunk 1]
```diff
@@ -262,4 +269,13 @@ public static void setListOfTrips(ArrayList<Trip> listOfTrips) {
         Storage.listOfTrips = listOfTrips;
     }
 
+    public static boolean isIsProcessing() {
```
Comment (lixiyuan416) [inline src/main/java/seedu/duke/Storage.java:272]: Consider just naming it isProcessing, this name is unholy haha
